spring: 
  profiles:
    active:
    - dev
---
server:
  port: 1004
  context-path: /
  
spring:
  profiles: dev
  application: 
    name: microservice-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: java
     
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student:1004 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      defaultZone: http://localhost:2004/eureka   #把服务注册到eureka注册中心
       
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   head: 张三
   phone: 110
---
server:
  port: 1004
  context-path: /
  
spring:
  profiles: test
  application: 
    name: microservice-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: java
     
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student:1004 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      defaultZone: http://localhost:2004/eureka   #把服务注册到eureka注册中心
       
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   head: 张三
   phone: 110